# Form implementation generated from reading ui file 'Ukrain.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainUkrain(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(614, 571)
        MainWindow.setStyleSheet("background-color:#ff99cf")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(260, 0, 101, 41))
        self.textBrowser.setStyleSheet("background-color:#ffffff")
        self.textBrowser.setObjectName("textBrowser")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 50, 591, 471))
        self.textEdit_2.setObjectName("textEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 614, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Україна</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px;\">В </span><span style=\" font-size:16px; font-weight:696;\">Вінниці </span><span style=\" font-size:16px;\">до Другої світової війни третина населення були євреями. Зараз у місті є кілька синагог, єврейські школи, єврейський цвинтар та житловий район Єрусалимка, а також тут відзначають єврейське свято Хануку.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px;\">В </span><span style=\" font-size:16px; font-weight:696;\">Дніпрі </span><span style=\" font-size:16px;\">знаходиться одна з найдовших і найбільш мальовничих у світі набережних. Вона простяглася на 23 кілометри.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px;\">У 2012 році в центрі </span><span style=\" font-size:16px; font-weight:696;\">Донецька</span><span style=\" font-size:16px;\"> був встановлений рекорд Гіннеса за наймасштабнішу квадриль (народний танець). У заході взяли участь понад 30 тисяч танцюристів.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px; font-weight:696;\">Житомир</span><span style=\" font-size:16px;\"> виробляє найбільше меду в Україні, а також чверть всього українського морозива.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px;\">В </span><span style=\" font-size:16px; font-weight:696;\">Запоріжжі</span><span style=\" font-size:16px;\"> був вироблений один з перших в СРСР тракторів, який був подарований Володимиру Леніну. Трактор мав примітивну конструкцію, але на ньому було легко працювати. Називався він &quot;Запорожець&quot;, як і відома марка машин.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px; font-weight:696;\">Івано-Франківськ</span><span style=\" font-size:16px;\"> раніше носив назву Станіславів і був столицею Західно-Української Народної Республіки в 1919 році. Свою сучасну назву отримав у 1962 році на 300-річчя міста.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px;\">В </span><span style=\" font-size:16px; font-weight:696;\">Києві</span><span style=\" font-size:16px;\"> знаходиться найглибша станція метро в світі - &quot;Арсенальна&quot;. Спуск на станцію на ескалаторі займає більше п\'яти хвилин.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px; font-weight:696;\">Кропивницький</span><span style=\" font-size:16px;\"> за свою історію змінив 6 назв. Зараз це єдиний в Україні обласний центр, який названий на честь театрального діяча - творця українського театру Марка Лукича Кропивницького</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px;\">Найстаріша вулиця </span><span style=\" font-size:16px; font-weight:696;\">Луганська</span><span style=\" font-size:16px;\"> раніше називалася Англійською і була єдиною вулицею в місті. На ній жили англійські інженери. Зараз вона носить назву вулиця Даля.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px;\">В </span><span style=\" font-size:16px; font-weight:696;\">Луцьку </span><span style=\" font-size:16px;\">знаходиться найдовший в Європі житловий будинок. Його сумарна довжина - понад 2,5 км, а всього в будинку 120 під\'їздів. </span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px; font-weight:696;\">Львів</span><span style=\" font-size:16px;\"> - найрізноманітніший в Україні релігійний центр. Тут представлені всі конфесії християнства, а також є синагога.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px;\">В </span><span style=\" font-size:16px; font-weight:696;\">Миколаєві </span><span style=\" font-size:16px;\">розташована одна з найстаріших в Європі морських обсерваторій. Вона є одним з найкрасивіших будівель в місті і найвищою точкою Миколаєва.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px;\">В </span><span style=\" font-size:16px; font-weight:696;\">Одесі</span><span style=\" font-size:16px;\"> є кілька будинків, побудованих під кутом в 45 градусів. Якщо подивитися на них збоку, то здається, що ці будинки плоскі.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px; font-weight:696;\">Полтава</span><span style=\" font-size:16px;\"> вважається батьківщиною української розмовної мови. Саме тут народився і жив Іван Котляревський, автор першої поеми українською мовою.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px;\">В </span><span style=\" font-size:16px; font-weight:696;\">Рівному</span><span style=\" font-size:16px;\"> був знайдений бурштин віком 40 мільйонів років, в якому були виявлені стародавні скорпіони, павуки, мурахи та інші комахи. Цей бурштин утворився в той час, коли територія України була островом, а на місці Польщі було море.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px;\">В </span><span style=\" font-size:16px; font-weight:696;\">Сімферополі </span><span style=\" font-size:16px;\">починається найдовший у світі тролейбусний маршрут. Закінчується він в Ялті. Його довжина - 86 кілометрів.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px;\">В </span><span style=\" font-size:16px; font-weight:696;\">Сумах </span><span style=\" font-size:16px;\">до початку 20 століття жило багато австрійців, чехів, німців, поляків та інших європейців. Вони опинялися в місті як біженці після Першої світової війни, а багатьох з них засилали вглиб Російської Імперії після невдалих повстань.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px;\">Центр </span><span style=\" font-size:16px; font-weight:696;\">Тернопіля</span><span style=\" font-size:16px;\"> прикрашає найбільший в Україні штучний ставок. Його площа становить понад 300 гектарів. На ньому розташований фонтан і ходять теплоходи, а взимку тут влаштовують хокейні змагання.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px; font-weight:696;\">Ужгород</span><span style=\" font-size:16px;\"> знаходиться ближче до Варшави, Кишинева і Праги, ніж до Києва.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px; font-weight:696;\">Харків </span><span style=\" font-size:16px;\">- одне з найбільш &quot;освічених&quot; міст України. Тут розташовано майже 80 вузів.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px;\">Під </span><span style=\" font-size:16px; font-weight:696;\">Херсоном</span><span style=\" font-size:16px;\"> розташована величезна мережа катакомб, звідки раніше добували глину для побудови старої частини міста.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px; font-weight:696;\">Хмельницький</span><span style=\" font-size:16px;\"> отримав назву на честь гетьмана Богдана Хмельницького і в ньому є аж 4 пам\'ятники полководцю. Однак сам гетьман ніколи не відвідував це місто.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px;\">В </span><span style=\" font-size:16px; font-weight:696;\">Черкасах </span><span style=\" font-size:16px;\">міг розташовуватися Родень - одне з найзагадковіших міст України, яке існувало у 8 столітті. Його точне розташування невідоме, але є припущення, що він знаходився на Замковій горі в Черкасах.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:8pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:14pt; font-weight:696;\">Чернігів</span><span style=\" font-size:14pt;\"> - одне з найстаріших міст України, історичний центр Лівобережної України та одне з найбільш населених міст Київської Русі.</span></li>\n"
"<li style=\" font-family:\'Inter,sans-serif\'; font-size:14pt; color:#25252c;\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:32px;\"><span style=\" font-size:16px;\">В </span><span style=\" font-size:16px; font-weight:696;\">Чернівцях</span><span style=\" font-size:16px;\"> щодня о 12:00 на міську ратушу піднімається трубач в національному костюмі і сурмить пісню &quot;Марічка&quot;.</span></li></ul></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainUkrain()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
